main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register, login_user, logout_user
from main.views import plus_product_amount, minus_product_amount, remove_product
from main.views import edit_product
from main.views import get_product_json, add_product_ajax
from main.views import plus_product_amount_ajax, remove_product_ajax, minus_product_amount_ajax
from main.views import create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('plus_product_amount/<int:id>', plus_product_amount, name='plus_product_amount'),
    path('minus_product_amount/<int:id>', minus_product_amount, name='minus_product_amount'),
    path('remove_product/<int:id>', remove_product, name='remove_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('plus_product_amount_ajax/<int:id>/', plus_product_amount_ajax, name='plus_product_amount_ajax'),
    path('minus_product_amount_ajax/<int:id>/', minus_product_amount_ajax, name='minus_product_amount_ajax'),
    path('remove_product_ajax/<int:id>/', remove_product_ajax, name='remove_product_ajax'),
    path('edit_product/<int:id>', edit_product, name='edit_product'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

oculi_archive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Oculi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    name = models.CharField(max_length=255)
    region = models.CharField(max_length=255)
    amount_collected = models.IntegerField()
    amount = models.IntegerField()
    description = models.TextField()

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import Oculi

class ProductForm(ModelForm):
    class Meta:
        model = Oculi
        fields = ["name", "region", "amount_collected", "amount", "description"]

main/views.py
from django.shortcuts import render
from .models import Oculi
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Oculi.objects.create(
            user = request.user,
            name = data["name"],
            region = data["region"],
            amount = int(data["amount"]),
            amount_collected = int(data["amount_collected"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
# Create your views here.
@login_required(login_url='/login')
def show_main(request):

    # Iterating through the data
    
    oculi = Oculi.objects.filter(user=request.user)
    if 'last_login' in request.COOKIES:
        last_login = request.COOKIES['last_login']
    else:
        last_login = 'N/A'  # Set a default value or handle the case when the key doesn't exist
    context = {
        'name' : request.user.username,
        'class' : "PBP-C",
        'oculus' : oculi,
        'last_login': last_login,
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Oculi.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def show_xml(request):
    data = Oculi.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Oculi.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Oculi.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Oculi.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def plus_product_amount(request, id):
    product = Oculi.objects.get(id=id)
    product.amount_collected += 1
    product.save()
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def minus_product_amount(request, id):
    product = Oculi.objects.get(id=id)
    if (product.amount > 0):
        product.amount_collected -= 1
        product.save()
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def remove_product(request, id):
    Oculi.objects.filter(pk=id).delete()
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def get_product_json(request):
    product_item = Oculi.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':

        user = request.user
        name = request.POST.get("name")
        region = request.POST.get("region")
        amount = request.POST.get("amount")
        amount_collected = request.POST.get("amount_collected")
        description = request.POST.get("description")

        new_product = Oculi(name=name, region=region, amount=amount, amount_collected=amount_collected, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def plus_product_amount_ajax(request, id):
    product = Oculi.objects.get(pk=id)
    product.amount_collected += 1
    product.save()
    return HttpResponse(b"ADD", status=201)

@csrf_exempt
def minus_product_amount_ajax(request, id):
    product = Oculi.objects.get(pk=id)
    if (product.amount > 0):
        product.amount_collected -= 1
        product.save()
        return HttpResponse(b"CREATED", status=201)
    else :
        return HttpResponse(b"NOT CREATED", status=201)

    
@csrf_exempt
def remove_product_ajax(request, id):
    Oculi.objects.filter(pk=id).delete()
    return HttpResponseRedirect(reverse("main:show_main"))

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <head>
            {% block meta %}
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
            {% endblock meta %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        </head>
    </head>

    <body> 
        <nav class="navbar navbar-expand-lg border-bottom border-body" data-bs-theme="dark" style="background-color: #435334;">
            <div class="container">
                <a class="navbar-brand" href="#">Logo nanti aja dah</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about/">About</a>
                        </li>
                        <!-- Add more menu items as needed -->
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container mt-4"> 
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

main/templates/challenge.html
<div>
    <table>
        <tr>
            <th>Nama</th>
            <th>NPM</th>
        </tr>
        <tr>
            <td>Rizki Maulana</td>
            <td>2206814425</td>
        </tr>
    </table>
</div>

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<style>
    .container-form {
        width: 50vw; /* Set the width to 50% of the viewport width */
        margin: 0 auto; /* Center the container horizontally */
        background-color: #9EB384; /* Add a background color for visualization */
        padding: 80px; /* Add padding for spacing within the container */
        padding-top: 30px;
        padding-bottom: 50px;
        border-radius: 10px;
        margin-bottom: 100px;
    }
    .heading-new {
        color: white;
        font-size: 40px;
        margin-bottom: 15px;
    }
</style>
<div class="container-form">
    <h1 class="heading-new">Add New Product</h1>
    <form method="POST" class="my-form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Product"/>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <style>
        .container.text-center {
            width: 50vw; /* Set the width to 50% of the viewport width */
            margin: 0 auto; /* Center the container horizontally */
            background-color: #9EB384; /* Add a background color for visualization */
            padding: 100px; /* Add padding for spacing within the container */
            border-radius: 10px;
        }
        .login-head {
            color: white;
            font-size: 40px;
        }
        .login {
            vertical-align: top;
        }

        .login-msg {
            color: white;
            font-size: 15px;
        }
    </style>
    <div class = "login">
        <div class = "container text-center">
            <div class = "row">
                <h1 class="login-head">Welcome to Rizmau's Website!</h1>
                <h2 class="login-msg">Please input your information to get in.</h2>
            </div>
            <div class = "row justify-content-center align-items-center">
                <form method="POST" action="">
                    {% csrf_token %}
                    <style>
                        table {
                            width: 100%;
                            border-collapse: collapse;
                            vertical-align: middle;
                        }
                        
                        th, td {
                            text-align: center;
                            vertical-align: middle;
                            padding: 10px; /* Add padding to style cells */
                        }
                    </style>
                    <table>
                        <tr>
                            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                        </tr>

                        <tr></tr>
                            <td><input class="btn btn-primary login_btn" type="submit" value="Login" style = "background-color: #435334; border:transparent"></td>
                        </tr>
                    </table>
                </form> 
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}     
                    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
            </div>
        </div>
    </div>
    {% endblock %} 
</body>

main/templates/login_sementara.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
{% block content %}
<body>
    <style>
        .btn{
            background-color: white; 
            border:transparent;
            color:#9EB384;
        }
        .btn.btn-main {
            background-color: #9EB384; 
            border:transparent;
            color:white;
        }
        .centered-text{
            text-align: center;
        }
        .card{
            background-color: #9EB384;
            border:transparent;
        }
        .card-header{
            border:transparent;
        }
        .centered-cards{
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .card-body p{ 
            color:#ffffff;
        }
        .container-card {
            margin: 0 auto; /* Center the container horizontally */
            padding: 80px; /* Add padding for spacing within the container */
            padding-top: 10px;
            padding-bottom: 50px;
            border-radius: 10px;
            margin-bottom: 100px;
        }
        .card:last-child {
            background-color:#e98e0e;
        }
        .card:last-child .card-header {
            background-color:#de8407;
        }
        .card:last-child button{
            color:#de8407;
        }
    </style>
    
    <div class="container">
        <h1>Resource Tracker</h1>
        <p> The thing is, Genshin Impact is my favourite game. Ever. There's sort of a wish in my bucket list. To make
            make a project to dedicate my skill but with the theme of my this game. So, I hope this will be the one. </p> 
        <a href="{% url 'main:create_product' %}">
            <button class="btn btn-main btn-primary">
                Add New Resources
            </button>
        </a>
    
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-main btn-primary">
                Logout
            </button>
        </a>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
    
    <table id="product_table"></table>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="region" class="col-form-label">Region:</label>
                            <input type="text" class="form-control" id="region" name="region"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount_collected" class="col-form-label">Amount Collected:</label>
                            <input type="number" class="form-control" id="amount_collected" name="amount_collected"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="card-container" class="row row-cols-1 g-4">
    </div>
</body>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("card-container").innerHTML = ""
        const products = await getProducts()

        let htmlString = ``

        products.forEach((item) => {
            htmlString += `\n
            <div class="card mb-3" style="max-width: 18rem; margin:10px">
                <div class="card-header" style="margin-top: 10px;">
                    <h2 style="color:white">${item.fields.name}</h2> 
                </div>
                <div class="card-body">
                    <p>Region: ${item.fields.region}</p>
                    <p>Amount collected: ${item.fields.amount_collected}</p>
                    <p>Total amount: ${item.fields.amount}</p>
                    <p>Description: ${item.fields.description}</p>   
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-primary" onclick="plus_product_ajax(${item.pk})">+</button>
                        </div>
                        <div class="col">
                            <button class="btn btn-primary" onclick="minus_product_ajax(${item.pk})">-</button>
                        </div>
                        <div class="col">
                            <button class="btn btn-primary" onclick="delete_product_ajax(${item.pk})">Delete</button>
                        </div>
                    </div>
                    <div class="row justify-content-center m" style="margin-top:10px;">
                        <div class="col">
                            <a href="edit_product/${item.pk}">
                                <button class="btn btn-primary btn-block" style="width:100%">
                                    Edit
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            ` 
        })
        
        document.getElementById("card-container").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        
        return false
    }

    function plus_product_ajax(ID) {
        fetch('/plus_product_amount_ajax/0/'.replace("0", ID), {
            method: 'POST',
        }).then(refreshProducts)

        return false
    }

    function minus_product_ajax(ID) {
        fetch('/minus_product_amount_ajax/0/'.replace("0", ID), {
            method: 'POST',
        }).then(refreshProducts)

        return false
    }

    function delete_product_ajax(ID) {
        fetch('/remove_product_ajax/0/'.replace("0", ID), {
            method: 'DELETE',
        }).then(refreshProducts)
    }
    document.getElementById("button_add").onclick = addProduct
</script>
{% endblock %} 
</html>

main/templates/main_dengan_card.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    {% block content %}
    <style>
        .btn{
            background-color: #9EB384; 
            border:transparent;
        }
        .centered-text{
            text-align: center;
        }
    </style>
    <div class="container mt-3">
        <h1>Resource Tracker</h1>
        <p> The thing is, Genshin Impact is my favourite game. Ever. There's sort of a wish in my bucket list. To make
            make a project to dedicate my skill but with the theme of my this game. So, I hope this will be the one. </p>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Region</th>
                    <th>Amount collected</th>
                    <th>Total amount</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for oculi in oculus %}
                <tr>
                    <td>{{oculi.name}}</td>
                    <td>{{oculi.region}}</td>
                    <td class="centered-text">{{oculi.amount_collected}}</td>
                    <td class="centered-text">{{oculi.amount}}</td>
                    <td>{{oculi.description}}</td>
                    <td class="d-flex align-items-center">
                        <form method="post" action="{% url 'main:plus_product_amount' oculi.id %}">
                            {% csrf_token %}
                            <button class="btn btn-primary mx-1"  >+</button>
                        </form>
                        <form method="post" action="{% url 'main:minus_product_amount' oculi.id %}">
                            {% csrf_token %}
                            <button class="btn btn-primary mx-1">-</button>
                        </form>
                        <form method="post" action="{% url 'main:remove_product' oculi.id %}">
                            {% csrf_token %}
                            <button class="btn btn-primary mx-1">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>  
    </div>
    
    <a href="{% url 'main:create_product' %}">
        <button class="btn btn-primary">
            Add New Resources
        </button>
    </a>

    <a href="{% url 'main:logout' %}">
        <button class="btn btn-primary">
            Logout
        </button>
    </a>

    <h5>Sesi terakhir login: {{ last_login }}</h5>
    
    {% endblock %} 
    <div class="container mt-3">
        {% for oculi in oculus %}
      <div class="card">
        <h2>{{oculi.name}}</h2>
        <p>Author: {{oculi.region}}</p>
        <p>Amount collected: {{oculi.amount_collected}}</p>
        <p>Total amount: {{oculi.amount}}</p>
        <p>Description: {{oculi.description}}</p>
      </div>
    {% endfor %}
    </div>
</body>
</html>

main/templates/main_sementara.html
{% extends 'base.html' %}

{% block content %}
<h1>Oculus Tracker</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Region</th>
        <th>Amount collected</th>
        <th>Total amount</th>
        <th>Description</th>
    </tr>

    {% comment %} Berikut cara memperlihatkan data produk di bawah baris ini {% endcomment %}

    {% for oculi in oculus %}
        <tr>
            <td>{{oculi.name}}</td>
            <td>{{oculi.region}}</td>
            <td>{{oculi.amount_collected}}</td>
            <td>{{oculi.amount}}</td>
            <td>{{oculi.description}}</td>
        </tr>
    {% endfor %}
</table>

<br />

<a href="{% url 'main:create_product' %}">
    <button>
        Add New Product
    </button>
</a>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }} 
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>   
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}